<?php

namespace DPC\FAQBundle\Repository;

/**
 * FaqThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqThemeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPublished(){
		return $this
		    ->createQueryBuilder('t')
		    ->leftJoin('t.faqs', 'f')
		    ->addSelect('f')
		    ->andWhere('f.published = true')
		    ->getQuery()
		    ->getResult();
	}
}
