<?php

namespace DPC\AdminBundle\Repository;

/**
 * ProductSearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSearchRepository extends \Doctrine\ORM\EntityRepository
{
}
