<?php

namespace DPC\ServiceBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllServices(){
		$qb = $this->createQueryBuilder('s');

		$query = $qb
	    ->leftJoin('s.image', 'i')
	    ->addSelect('i')
	    ->leftJoin('s.category', 'c')
	    ->addSelect('c')
		->getQuery();

		return $query->getResult();
	}
	public function findServiceWithImage($id){
		$qb = $this->createQueryBuilder('s');

		$query = $qb
		->andWhere('s.id = :id')
	    ->setParameter('id', $id)
	    ->leftJoin('s.image', 'i')
	    ->addSelect('i')
	    ->leftJoin('s.category', 'c')
	    ->addSelect('c')
		->getQuery();

		return $query->getOneOrNullResult();
	}
}
