<?php

namespace DPC\ContactBundle\Repository;

/**
 * CompanyInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyInformationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getContactInformation(){
		
		$qb = $this->createQueryBuilder('c');

		$query = $qb
	    ->leftJoin('c.logo', 'l')
	    ->addSelect('l')
	    ->setMaxResults(1)
		->getQuery();

		return $query->getOneOrNullResult();
	}
}
