# Routes produits

dpc_store_product:
    path:     /catalogue/fiche-produit/{id}
    defaults: 
        _controller: DPCStoreBundle:Store:productDetail
    requirements: 
        id: \d+
        category: \w+

dpc_store_promotions:
    path:     /promotions/{page}
    defaults: { _controller: DPCStoreBundle:Store:promotions }
    requirements: 
        page: \d+
    
dpc_store_occasions:
    path:     /occasions/{page}
    defaults: { _controller: DPCStoreBundle:Store:occasions }
    requirements: 
        page: \d+

dpc_store_catalogue:
    path:     /dpc-catalogue/{page}
    defaults: { _controller: DPCStoreBundle:Store:catalogue }
    requirements: 
        page: \d+

dpc_store_brand:
    path:     /brand/{id}
    defaults: 
        _controller: DPCStoreBundle:Store:brand
    requirements: 
        id: \d+



