<?php

namespace DPC\StoreBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLastPromos(){
		$qb = $this->createQueryBuilder('p');

		$query = $qb
		->andWhere('p.promo = true')
		->getQuery();

		return $query->getResult();
	}

	public function getLastOccasions(){
		$qb = $this->createQueryBuilder('p');

		$query = $qb
		->andWhere('p.occasion = true')
		->getQuery();

		return $query->getResult();
	}
}
