services:
    contact_mailer:
        class: DPC\ContactBundle\Service\ContactMailer
        arguments:
            - "@mailer"
            - %contact_mailer_admin_mail%
            - "@templating"

parameters:
    contact_mailer_admin_mail: beau.antony@gmail.com