<?php

namespace DPC\HomeBundle\Repository;

/**
 * HomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getHomeWithSections(){
			    //->setParameter('id', $id)
		$qb = $this->createQueryBuilder('h');

		$query = $qb
		->leftJoin('h.sectionOne', 's1')
	    ->addSelect('s1')
	    ->leftJoin('h.sectionTwo', 's2')
	    ->addSelect('s2')
	    ->leftJoin('h.sectionThreeElements', 's3')
	    ->addSelect('s3')
	    ->leftJoin('h.sectionFourElements', 's4')
	    ->addSelect('s4')
	    ->leftJoin('s4.image', 's4i')
	    ->addSelect('s4i')
	    ->leftJoin('h.slides', 'sl')
	    ->addSelect('sl')
	    ->setMaxResults(1)
		->getQuery();

		return $query->getOneOrNullResult();
	}
}
