<?php

namespace DPC\HomeBundle\Repository;

/**
 * SectionTwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionTwoRepository extends \Doctrine\ORM\EntityRepository
{
}
