<?php

namespace DPC\HomeBundle\Repository;

/**
 * SectionThreeElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionThreeElementRepository extends \Doctrine\ORM\EntityRepository
{
}
