<?php

namespace DPC\HomeBundle\Repository;

/**
 * SectionOneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionOneRepository extends \Doctrine\ORM\EntityRepository
{
}
