<?php

namespace DPC\HomeBundle\Repository;

/**
 * SectionThreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionThreeRepository extends \Doctrine\ORM\EntityRepository
{
}
