<?php

namespace DPC\HomeBundle\Repository;

/**
 * SectionFourElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionFourElementRepository extends \Doctrine\ORM\EntityRepository
{
}
